### ISSUE TITLE
jr_visca_handleAckCompletionParameters off by one error

### ISSUE THREAD

**Issue by lrucker1** [elodotwe/libjr_visca#1]
jr_visca_handleAckCompletionParameters
        frame->data[0] += messageParameters->ackCompletionParameters.socketNumber;

It only has one byte of data; this should be "data[0]". It's mostly harmless here, but I discovered it while adding a error/cancel reply which is 2 bytes, where it changed my reply type instead of the socket.

**Comment by elodotwe** [comment]
You're absolutely correct, sorry that caught you out!

You actually helped me find another bug, #2 ("wait, so what keeps these `handle*Parameters()` functions from going out of bounds of the frame data? Uhh....nothing..."); thank you for spurring the thought along.

Quick test case hacked up (using some defs from `jr_visca_tester.c`, that kinda needs some work doesn't it?),
```c
    union jr_viscaMessageParameters parameters;
    parameters.ackCompletionParameters.socketNumber = 3;
    uint8_t expectedData[] = {0x90, 0x43, 0xff};
    assertEncodedMessage(JR_VISCA_MESSAGE_ACK, parameters, 1, 0, expectedData, sizeof(expectedData), __LINE__);
```
results in
```
expected 90 43 ff , actual 90 40 ff 
line 69: data should be well formed
```

Likewise I'm not decoding ACKs correctly...
```c
    uint8_t encoded[] = {0x90, 0x42, 0xff};
    int message = 0;
    union jr_viscaMessageParameters parameters;
    uint8_t sender = 0;
    uint8_t receiver = 0;
    jr_viscaDecodeMessage(encoded, sizeof(encoded), &message, &parameters, &sender, &receiver);
    // parameters.ackCompletionParameters.socketNumber should be 2, is currently 0 (when running with a clean buffer! likely depends on previously decoded messages, yikes!)
```

**Comment by elodotwe** [comment]
This should be fixed now-- let me know how you get on with it. There's definitely some robustifying this needs at some point, I may get to it somewhere in the near future (this is a hobby project, but your interest sparked mine and I'm on holiday at the moment so this was a nice exercise, thank you!).

**Comment by lrucker1** [comment]
Thanks! Yes, that’s the change I’d made, it works great. I’ve been adding lots of new commands; once it’s stable I’ll make up a change request. I’ve been using this to test a utility app I’m writing; we run livestreams for a university church, so my access to the physical cameras is limited and your simulator has been invaluable. I could take a camera home but it’s a hassle.
